version: '3.7'

services:
  db:
    container_name: database
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: theflock
    tty: true
    volumes: 
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    container_name: app
    build:
      context: .
    env_file: ./.env.local
    depends_on:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
      - 127.0.0.1:9223:9223
    environment:
      - HOST_DB=database
    command: npm run start
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:3306",
        "--",
        "npm",
        "run",
        "migrate"
      ]
    links:
      - db
    depends_on:
      - db
    env_file: ./.env.local
    environment:
      - HOST_DB=database
volumes:
  mysql_data: null